import { StockBookDTO } from "@/application/controller/dto/StockBookDto";

export const INPUT_BOOK: StockBookDTO = {
	title: "Domain-Driven Design",
	edition: 1,
	author: "Eric Evans",
	releaseDate: "2003-08-22T03:00:00.000Z",
	cover: "https://m.media-amazon.com/images/I/51OWGtzQLLL._SY342_.jpg",
	category: "technology",
	quantity: 15,
	isVisible: true,
	unitPrice: 50,
};

export class MockInputBook {
	constructor(
		public title: string = "Domain-Driven Design",
		public edition: number = 1,
		public author: string = "Eric Evans",
		public releaseDate: string = "2003-08-22",
		public cover: string = "https://m.media-amazon.com/images/I/51OWGtzQLLL._SY342_.jpg",
		public category: string = "technology",
		public quantity: number = 15,
		public isVisible: boolean = true,
		public unitPrice: number = 50
	) {}
}

export const mockBooks = [
	{
		title: "Domain Driven Design",
		edition: 1,
		author: "Eric Evans",
		releaseDate: "2003-08-20",
		cover: "domain_driven_design.jpg",
		category: "Software Development",
		quantity: 50,
		isVisible: true,
		unitPrice: 25.99,
	},
	{
		title: "Building Microservices: Designing Fine-Grained Systems",
		edition: 1,
		author: "Sam Newman",
		releaseDate: "2015-02-20",
		cover: "building_microservices.jpg",
		category: "Software Development",
		quantity: 40,
		isVisible: true,
		unitPrice: 28.99,
	},
	{
		title: "Clean Code: A Handbook of Agile Software Craftsmanship",
		edition: 1,
		author: "Robert C. Martin",
		releaseDate: "2008-08-11",
		cover: "clean_code.jpg",
		category: "Software Development",
		quantity: 55,
		isVisible: true,
		unitPrice: 32.99,
	},
	{
		title: "Refactoring: Improving the Design of Existing Code",
		edition: 2,
		author: "Martin Fowler",
		releaseDate: "2018-06-21",
		cover: "refactoring.jpg",
		category: "Software Development",
		quantity: 45,
		isVisible: true,
		unitPrice: 27.99,
	},
	{
		title:
			"Continuous Delivery: Reliable Software releaseDates through Build, Test, and Deployment Automation",
		edition: 1,
		author: "Jez Humble and David Farley",
		releaseDate: "2010-08-10",
		cover: "continuous_delivery.jpg",
		category: "Software Development",
		quantity: 60,
		isVisible: true,
		unitPrice: 29.99,
	},
	{
		title: "The Pragmatic Programmer: Your Journey to Mastery",
		edition: 2,
		author: "Andrew Hunt and David Thomas",
		releaseDate: "2019-10-11",
		cover: "pragmatic_programmer.jpg",
		category: "Software Development",
		quantity: 65,
		isVisible: true,
		unitPrice: 34.99,
	},
	{
		title: "Design Patterns: Elements of Reusable Object-Oriented Software",
		edition: 1,
		author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
		releaseDate: "1994-10-10",
		cover: "design_patterns.jpg",
		category: "Software Development",
		quantity: 70,
		isVisible: true,
		unitPrice: 31.99,
	},
	{
		title: "Head First Design Patterns",
		edition: 1,
		author: "Eric Freeman, Elisabeth Robson, Bert Bates, Kathy Sierra",
		releaseDate: "2004-09-30",
		cover: "head_first_design_patterns.jpg",
		category: "Software Development",
		quantity: 75,
		isVisible: true,
		unitPrice: 33.99,
	},
	{
		title:
			"Clean Architecture: A Craftsman's Guide to Software Structure and Design",
		edition: 1,
		author: "Robert C. Martin",
		releaseDate: "2017-09-20",
		cover: "clean_architecture.jpg",
		category: "Software Development",
		quantity: 80,
		isVisible: true,
		unitPrice: 36.99,
	},
	{
		title: "Test Driven Development: By Example",
		edition: 1,
		author: "Kent Beck",
		releaseDate: "2002-11-18",
		cover: "test_driven_development.jpg",
		category: "Software Development",
		quantity: 85,
		isVisible: true,
		unitPrice: 30.99,
	},
	{
		title: "Practical Object-Oriented Design: An Agile Primer Using Ruby",
		edition: 2,
		author: "Sandi Metz",
		releaseDate: "2012-08-14",
		cover: "practical_object_oriented_design.jpg",
		category: "Software Development",
		quantity: 90,
		isVisible: true,
		unitPrice: 26.99,
	},
	{
		title: "The Clean Coder: A Code of Conduct for Professional Programmers",
		edition: 1,
		author: "Robert C. Martin",
		releaseDate: "2011-05-13",
		cover: "clean_coder.jpg",
		category: "Software Development",
		quantity: 95,
		isVisible: true,
		unitPrice: 28.99,
	},
	{
		title: "Domain-Driven Design Distilled",
		edition: 1,
		author: "Vaughn Vernon",
		releaseDate: "2016-12-26",
		cover: "domain_driven_design_distilled.jpg",
		category: "Software Development",
		quantity: 100,
		isVisible: true,
		unitPrice: 29.99,
	},
	{
		title: "Refactoring to Patterns",
		edition: 1,
		author: "Joshua Kerievsky",
		releaseDate: "2004-08-09",
		cover: "refactoring_to_patterns.jpg",
		category: "Software Development",
		quantity: 105,
		isVisible: true,
		unitPrice: 32.99,
	},
	{
		title: "Code Complete: A Practical Handbook of Software Construction",
		edition: 2,
		author: "Steve McConnell",
		releaseDate: "2004-06-09",
		cover: "code_complete.jpg",
		category: "Software Development",
		quantity: 110,
		isVisible: true,
		unitPrice: 35.99,
	},
	{
		title: "The Mythical Man-Month: Essays on Software Engineering",
		edition: 1,
		author: "Frederick P. Brooks Jr.",
		releaseDate: "1995-08-12",
		cover: "mythical_man_month.jpg",
		category: "Software Development",
		quantity: 115,
		isVisible: true,
		unitPrice: 33.99,
	},
	{
		title: "Head First Java",
		edition: 1,
		author: "Kathy Sierra, Bert Bates",
		releaseDate: "2005-02-09",
		cover: "head_first_java.jpg",
		category: "Software Development",
		quantity: 120,
		isVisible: true,
		unitPrice: 37.99,
	},
	{
		title: "Clean Agile: Back to Basics",
		edition: 1,
		author: "Robert C. Martin",
		releaseDate: "2019-11-29",
		cover: "clean_agile.jpg",
		category: "Software Development",
		quantity: 125,
		isVisible: true,
		unitPrice: 39.99,
	},
	{
		title: "Agile Principles, Patterns, and Practices in C#",
		edition: 1,
		author: "Robert C. Martin, Micah Martin",
		releaseDate: "2006-08-11",
		cover: "agile_principles_patterns_and_practices_in_csharp.jpg",
		category: "Software Development",
		quantity: 130,
		isVisible: true,
		unitPrice: 34.99,
	},
	{
		title: "Effective Java",
		edition: 3,
		author: "Joshua Bloch",
		releaseDate: "2017-12-27",
		cover: "effective_java.jpg",
		category: "Software Development",
		quantity: 135,
		isVisible: true,
		unitPrice: 36.99,
	},
	{
		title: "Patterns of Enterprise Application Architecture",
		edition: 1,
		author: "Martin Fowler",
		releaseDate: "2002-11-15",
		cover: "patterns_of_enterprise_application_architecture.jpg",
		category: "Software Development",
		quantity: 140,
		isVisible: true,
		unitPrice: 39.99,
	},
	{
		title: "The Art of Unit Testing: With Examples in .NET",
		edition: 3,
		author: "Roy Osherove",
		releaseDate: "2013-10-05",
		cover: "art_of_unit_testing.jpg",
		category: "Software Development",
		quantity: 145,
		isVisible: true,
		unitPrice: 32.99,
	},
	{
		title: "Extreme Programming Explained: Embrace Change",
		edition: 2,
		author: "Kent Beck, Cynthia Andres",
		releaseDate: "2004-11-16",
		cover: "extreme_programming_explained.jpg",
		category: "Software Development",
		quantity: 150,
		isVisible: true,
		unitPrice: 31.99,
	},
	{
		title:
			"Software Engineering at Google: Lessons Learned from Programming Over Time",
		edition: 1,
		author: "Titus Winters, Tom Manshreck, Hyrum Wright",
		releaseDate: "2020-02-18",
		cover: "software_engineering_at_google.jpg",
		category: "Software Development",
		quantity: 155,
		isVisible: true,
		unitPrice: 38.99,
	},
	{
		title:
			"The Lean Startup: How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses",
		edition: 1,
		author: "Eric Ries",
		releaseDate: "2011-09-13",
		cover: "the_lean_startup.jpg",
		category: "Business",
		quantity: 160,
		isVisible: true,
		unitPrice: 29.99,
	},
	{
		title: "Zero to One: Notes on Startups, or How to Build the Future",
		edition: 1,
		author: "Peter Thiel, Blake Masters",
		releaseDate: "2014-09-16",
		cover: "zero_to_one.jpg",
		category: "Business",
		quantity: 165,
		isVisible: true,
		unitPrice: 32.99,
	},
	{
		title: "Hooked: How to Build Habit-Forming Products",
		edition: 1,
		author: "Nir Eyal, Ryan Hoover",
		releaseDate: "2014-11-04",
		cover: "hooked.jpg",
		category: "Business",
		quantity: 170,
		isVisible: true,
		unitPrice: 27.99,
	},
	{
		title: "Lean Analytics: Use Data to Build a Better Startup Faster",
		edition: 1,
		author: "Alistair Croll, Benjamin Yoskovitz",
		releaseDate: "2013-03-08",
		cover: "lean_analytics.jpg",
		category: "Business",
		quantity: 175,
		isVisible: true,
		unitPrice: 24.99,
	},
	{
		title:
			"The Startup Owner's Manual: The Step-By-Step Guide for Building a Great Company",
		edition: 1,
		author: "Steve Blank, Bob Dorf",
		releaseDate: "2012-03-01",
		cover: "the_startup_owners_manual.jpg",
		category: "Business",
		quantity: 180,
		isVisible: true,
		unitPrice: 39.99,
	},
	{
		title:
			"Measure What Matters: Online Tools for Understanding Customers, Social Media, Engagement, and Key Relationships",
		edition: 1,
		author: "Katie Delahaye Paine",
		releaseDate: "2011-10-24",
		cover: "measure_what_matters.jpg",
		category: "Business",
		quantity: 185,
		isVisible: true,
		unitPrice: 35.99,
	},
	{
		title:
			"Sprint: How to Solve Big Problems and Test New Ideas in Just Five Days",
		edition: 1,
		author: "Jake Knapp, John Zeratsky, Braden Kowitz",
		releaseDate: "2016-03-08",
		cover: "sprint.jpg",
		category: "Business",
		quantity: 190,
		isVisible: true,
		unitPrice: 33.99,
	},
	{
		title:
			"The Lean Product Playbook: How to Innovate with Minimum Viable Products and Rapid Customer Feedback",
		edition: 1,
		author: "Dan Olsen",
		releaseDate: "2015-05-18",
		cover: "the_lean_product_playbook.jpg",
		category: "Business",
		quantity: 195,
		isVisible: true,
		unitPrice: 28.99,
	},
	{
		title:
			"Blue Ocean Strategy: How to Create Uncontested Market Space and Make the Competition Irrelevant",
		edition: 1,
		author: "W. Chan Kim, Renée Mauborgne",
		releaseDate: "2005-02-03",
		cover: "blue_ocean_strategy.jpg",
		category: "Business",
		quantity: 200,
		isVisible: true,
		unitPrice: 36.99,
	},
	{
		title:
			"Good to Great: Why Some Companies Make the Leap... and Others Don't",
		edition: 1,
		author: "Jim Collins",
		releaseDate: "2001-10-16",
		cover: "good_to_great.jpg",
		category: "Business",
		quantity: 205,
		isVisible: true,
		unitPrice: 29.99,
	},
	{
		title: "Thinking, Fast and Slow",
		edition: 1,
		author: "Daniel Kahneman",
		releaseDate: "2011-10-25",
		cover: "thinking_fast_and_slow.jpg",
		category: "Psychology",
		quantity: 210,
		isVisible: true,
		unitPrice: 32.99,
	},
	{
		title: "The Power of Habit: Why We Do What We Do in Life and Business",
		edition: 1,
		author: "Charles Duhigg",
		releaseDate: "2012-02-28",
		cover: "the_power_of_habit.jpg",
		category: "Psychology",
		quantity: 215,
		isVisible: true,
		unitPrice: 26.99,
	},
	{
		title: "Blink: The Power of Thinking Without Thinking",
		edition: 1,
		author: "Malcolm Gladwell",
		releaseDate: "2005-01-11",
		cover: "blink.jpg",
		category: "Psychology",
		quantity: 220,
		isVisible: true,
		unitPrice: 30.99,
	},
	{
		title: "Drive: The Surprising Truth About What Motivates Us",
		edition: 1,
		author: "Daniel H. Pink",
		releaseDate: "2009-12-29",
		cover: "drive.jpg",
		category: "Psychology",
		quantity: 225,
		isVisible: true,
		unitPrice: 34.99,
	},
	{
		title: "Influence: The Psychology of Persuasion",
		edition: 1,
		author: "Robert B. Cialdini",
		releaseDate: "1984-12-31",
		cover: "influence.jpg",
		category: "Psychology",
		quantity: 230,
		isVisible: true,
		unitPrice: 27.99,
	},
	{
		title: "Outliers: The Story of Success",
		edition: 1,
		author: "Malcolm Gladwell",
		releaseDate: "2008-11-18",
		cover: "outliers.jpg",
		category: "Psychology",
		quantity: 235,
		isVisible: true,
		unitPrice: 29.99,
	},
	{
		title: "The Tipping Point: How Little Things Can Make a Big Difference",
		edition: 1,
		author: "Malcolm Gladwell",
		releaseDate: "2000-01-07",
		cover: "the_tipping_point.jpg",
		category: "Psychology",
		quantity: 240,
		isVisible: true,
		unitPrice: 25.99,
	},
	{
		title:
			"Thinking in Bets: Making Smarter Decisions When You Don't Have All the Facts",
		edition: 1,
		author: "Annie Duke",
		releaseDate: "2018-02-06",
		cover: "thinking_in_bets.jpg",
		category: "Psychology",
		quantity: 245,
		isVisible: true,
		unitPrice: 31.99,
	},
	{
		title: "Nudge: Improving Decisions About Health, Wealth, and Happiness",
		edition: 1,
		author: "Richard H. Thaler, Cass R. Sunstein",
		releaseDate: "2008-02-24",
		cover: "nudge.jpg",
		category: "Psychology",
		quantity: 250,
		isVisible: true,
		unitPrice: 28.99,
	},
];
